## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
    # - nightly
notifications:
  email: false
git:
  depth: 99999999

# uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
 allow_failures:
 - julia: nightly

env:
  global:
    - DOCUMENTER_DEBUG=true

jobs:
  include:
    - stage: "Documentation"
      julia: nightly
      os: osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip

after_success:
  # push coverage results to Codecov
  # - julia -e 'using Pkg; cd(Pkg.dir("FunnyTN")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("FunnyTN")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
